[package]
name = "schema"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "schema"

[dependencies]
schemars = "0.8.12"
serde_json = "1.0.96"
